# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='label')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geometry')),
                ('simplified_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='simplified geometry')),
            ],
            options={
                'ordering': ('layer__name', 'label'),
                'verbose_name_plural': 'boundaries',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('source_file', models.FileField(upload_to=b'places_boundary_layers', verbose_name='source file')),
            ],
        ),
        migrations.AddField(
            model_name='boundary',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundaries.Layer', verbose_name='layer'),
        ),
    ]
